### send form :
POST http://localhost:3000/form/post
Content-Type: application/json

{
  "communityName": "go senayan",
  "communityField": "penghijauan senayan",
  "communityContact": "123019284",
  "email": "gosenayan@gmail.com",
  "instagram": "some instagram link"
}


### CREATE ACCOUNT :
### sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "hdsvidi@gmail.com",
  "password": "Acomnn1@"

}

### sign in - get access token
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "youremail@gmail.com",
  "password": "Acomnn1@02"

}


### current - cek yourtoken valid
GET http://localhost:3000/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJjZDc4Njk4MzE3NGFjMDZjNWM5ZWUiLCJlbWFpbCI6Imhkc3ZpZGlAZ21haWwuY29tIiwiaWF0IjoxNjk3NDQxMTM4LCJleHAiOjE2OTg2NTA3Mzh9.T419XciW3Xq75HktOwGXqCXeFE2NbHz1k0DEwieNaPE

### update - user
PATCH http://localhost:3000/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJjZDc4Njk4MzE3NGFjMDZjNWM5ZWUiLCJlbWFpbCI6Imhkc3ZpZGlAZ21haWwuY29tIiwiaWF0IjoxNjk3NDQxMTM4LCJleHAiOjE2OTg2NTA3Mzh9.T419XciW3Xq75HktOwGXqCXeFE2NbHz1k0DEwieNaPE
Content-Type: application/json

{
  "oldPassword": "Acomnn1@",
  "newPassword": "Acomnn1@02"
}

